### ISSUE TITLE
Release 0.16.3.2

### ISSUE THREAD

**Issue by cryptapus** [riecointeam/riecoin#13]
On hold until CSV/Segwit activation. v0.16.3.2 will be a cleanup release for BIP65 and BIP66 along with transaction version and default address type.

**Comment by cryptapus** [comment]
Relevant PRs: #14 #11 #12

**Comment by Pttn** [comment]
Probably a release with such minor changes would not really be worth it. We should directly release 0.16.4 with GMP port, improved PoW and  difficulty adjustment. I am merging 0.16.3.2 and 0.16.4 milestones. And then catch up with 0.18+.

**Comment by cryptapus** [comment]
Agreed. Post softfork changes have been merged in preparation for a future release.
