### ISSUE TITLE
BIP9 Majority Threshold Discussion

### ISSUE THREAD

**Issue by cryptapus** [riecointeam/riecoin#16]
Now that v0.16.3.0 has been released we can observe adoption and discuss a plan to alter the 95% signalling requirement for BIP9 soft-fork activation.

In #6 I noted Riecoin has a short block window which may add risk to lowering the requirement. I would recommend that we wait to see what percentage we can reach at steady-state to proceed with a change. I would recommend using a different dummy bit (say `2`) so that v0.16.3.0 nodes are warned of such a change at least while it's being signaled.

**Comment by cryptapus** [comment]
Of coarse, a first-order requirement might be that we achieve >51% initially.

**Comment by Pttn** [comment]
RLGzid... recently upgraded, and remaining outdated big miners are RG6ZoZ... and RiePool. They have about 20-30% total mining power but now we are definitively > 50% with a solid margin.
The question is now if we should lower the requirement, or just wait and hope that either both upgrade or new 0.16.3 big miners come and lower their contribution to less than 5%.

**Comment by guytp** [comment]
I agree on 95% being too high.  If we're not seeing movement and want to position Riecoin for future growth we really want to cut legacy ASAP.  I'd be happy looking at something in the 60-75% region.  We'd need to see a /lot/ of increase in mining for the current .10.2 to be 5% - just over 300 new nodes.

**Comment by cryptapus** [comment]
The main issue I see if considering lower the threshold is the relatively short 288 block window period. This could be an issue if a large single miner wishes to force consensus with a short burst of mining hashpower. I would propose increasing the block period if we consider lowering the threshold.

**Comment by Pttn** [comment]
I think that most of the important people in the Riecoin community agrees to lower to 75%. If we stay at 95% the activation just won't happen because of those non cooperating miners. If these miners don't agree they can just continue mining alone in their own fork but we should not be retained by them. The upgrade eventually has to happen.

**Comment by Pttn** [comment]
As #19 was merged I am closing this
