### ISSUE TITLE
Initial sync broken

### ISSUE THREAD

**Issue by Pttn** [riecointeam/riecoin#17]
New people came in the Discord server, and we just discovered that the wallet is just not syncing at all from scratch. To experience it, just move/delete temporarily your blockchain, no sync is happening. Tested in Debian 8, Debian 9, Windows 10. This is a serious issue that needs to be fixed as soon as possible as it will deter new people from using Riecoin. @clo-prime @cryptapus 

That is weird, I am pretty sure that this worked fine from scratch in the past. If we use a bootstrap it syncs correctly though.

Fixing this is also the occasion to lower the activation threshold to like 75% as we can wait forever if we stay at 95%. Increase the window if needed but 95% is definitively too much in our case.

**Comment by Pttn** [comment]
Another workaround is just to add 0.16.3 nodes from https://chainz.cryptoid.info/ric/#!network
So it might be just that the current hard coded nodes are no longer active/reliable. If so we would need to ask people for more, reliable nodes.

**Comment by cryptapus** [comment]
I have just refreshed my dns seeds, perhaps they are getting stale. It would be helpful if more folks are able to run some dns seeds:

https://github.com/riecointeam/riecoin/blob/master/src/chainparams.cpp#L141

One could run `nslookup riecoinseed1.cryptapus.org` as an example.

Regarding lowering the activation, we can discuss on PR #19 after some examination.

**Comment by Pttn** [comment]
Now it is syncing fine for scratch, though we should have more than only one (I assume that all the *.riecoin.org ones are dead).
Someone provided a few node seeds, but I am still asking for DNS seeds in the Discord server.

**Comment by cryptapus** [comment]
Is anyone interested in running a DNS host like mine? We can add it to chainparams.

**Comment by Pttn** [comment]
XPoolX will try to set one. I also asked Ziiip and Guytp, not sure if they will.

**Comment by Pttn** [comment]
Unfortunately not much interest :| And XpoolX may need a week to set up one as he is pretty busy.
If no ones shares any DNS seeds until May 5 we will make the 0.16.3.1 release anyway and add DNS seeds only in 0.16.3.2.
Would you be in charge of the builds like for 0.16.3.0?

**Comment by Pttn** [comment]
Otherwise is there a way to force using the built-in node seeds? As I at least have a list of additional _node_ seeds.
Even when your DNS was down, the already hard coded nodes were still active... Why was the wallet not connecting to them without having to use a bootstrap or doing `addnode=...` ?

**Comment by cryptapus** [comment]
As I recall, nodes will request one IP from a dnsseed on startup. Only if DNS is not available does it go to the hard-coded ones. Even then it is possible some of the nodes are rate-limited as it can be configured on a per-node basis. In the DNS case if a particular node on `riecoinseed1.cryptapus.org` round-robin is down it won't try again until a restart. Perhaps I have too many unreliable nodes, hence a second or third DNS provider would be helpful. I *could* add and setup a `riecoinseed2` and `riecoinseed3` however that would seem to be a bit too centralized in my hands, would prefer some external help here.

**Comment by cryptapus** [comment]
> Would you be in charge of the builds like for 0.16.3.0?

I *can* tag and build the release, I would encourage others to give it a try as it is reproducable. I recommend following the gitian guide here:

https://github.com/riecointeam/docs/blob/master/gitian-building.md

then building with something like:

    ./bin/gbuild --commit riecoin=${COMMIT} --url riecoin=${URL} ../riecoin/contrib/gitian-descriptors/gitian-linux.yml
    (etc...)

(from https://github.com/riecointeam/docs/blob/master/gitian-building/gitian-building-manual.md#building-an-alternative-repository)

**Comment by Pttn** [comment]
Ok, I will give a try. Also maybe a second person will provide a DNS seed.

**Comment by Pttn** [comment]
Unfortunately nobody was able to set up a DNS seed yet. Adding some have to be postponed to 0.16.3.2 as the priority is to get everyone with the lower threshold. I will try to build today.

**Comment by Pttn** [comment]
Well, there does not seem to be much interest in providing nodes and DNS seeds... Hardcoding current nodes from for example CryptoID will be enough until we get more motivated people, I am closing this.
