### ISSUE TITLE
Plan rc0 tag

### ISSUE THREAD

**Issue by cryptapus** [riecointeam/riecoin#4]
Unless there are any objections, I'll plan to attempt a `beta0` test build via gitian on wk1903.

**Comment by Pttn** [comment]
I support this. We should also set some deadlines for Release Candidate and final version as no major problem were reported since clo1 released the code months ago.
We could make a RC build on early February (Week 1906) and the final release 1 month later (Week 1910)?

**Comment by cryptapus** [comment]
If #6 is merged, I don't see any reason why we couldn't move to a release fairly quickly since it allows flexible upgrades via BIP9. If a `beta0` release proves gitian is working well I will propose a quick move to `RC0` and a couple of weeks to confirm mining BIP9 blocks isn't forking anything.

**Comment by cryptapus** [comment]
v0.16.3.0-rc0 released

https://github.com/riecointeam/riecoin/releases/tag/v0.16.3.0-rc0
