### ISSUE TITLE
Release 0.16.3.0

### ISSUE THREAD

**Issue by cryptapus** [riecointeam/riecoin#7]
~2 weeks after rc0 if no issues are found and mining BIP9 blocks show no issues

**Comment by cryptapus** [comment]
Will be handling releases in the `0.16` branch for all 0.16 versions.

**Comment by cryptapus** [comment]
Planned ~wk1904 if no major issues are found in v0.16.3.0-rc0

**Comment by cryptapus** [comment]
I have out of band confirmation that a pool is successfully mining BIP9 blocks. I will tag a full release in a day or two if there are no objections.

**Comment by Pttn** [comment]
Yes, XpoolX confirmed that they upgraded the pool to 0.16.3 the January 17.

**Comment by Pttn** [comment]
Should we already lower the softforks activation threshold to 75% for Stable release?
At 95%, a single miner not upgrading/cooperating among "All Others", RiePool, RSoTqU..., RLGzid... or RGsGkJ... is enough to prevent activation (or delay it for an unneeded long amount of time) while the community seem to agree to activate.

**Comment by cryptapus** [comment]
As discussed in #6 Riecoin's short block window may be a risk... My impression is that we should see where a full release puts us and make a decision once we reach steady-state signalling percentage on lowering the threshold using a different bit (probably `2`).

**Comment by cryptapus** [comment]
released wk1904
